// Unity Build generated by CMake
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/src/function/scalar/variant/variant_utils.cpp>
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/src/function/scalar/variant/variant_extract.cpp>
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/src/function/scalar/variant/variant_typeof.cpp>
