// Unity Build generated by CMake
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/src/main/capi/cast/utils-c.cpp>
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/src/main/capi/cast/from_decimal-c.cpp>
