// Unity Build generated by CMake
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/extension/parquet/reader/variant/variant_binary_decoder.cpp>
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/extension/parquet/reader/variant/variant_value.cpp>
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/extension/parquet/reader/variant/variant_shredded_conversion.cpp>
