// Unity Build generated by CMake
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/src/common/arrow/arrow_appender.cpp>
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/src/common/arrow/arrow_converter.cpp>
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/src/common/arrow/arrow_type_extension.cpp>
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/src/common/arrow/arrow_merge_event.cpp>
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/src/common/arrow/arrow_query_result.cpp>
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/src/common/arrow/arrow_util.cpp>
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/src/common/arrow/arrow_wrapper.cpp>
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/src/common/arrow/physical_arrow_collector.cpp>
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/src/common/arrow/physical_arrow_batch_collector.cpp>
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/src/common/arrow/schema_metadata.cpp>
