// Unity Build generated by CMake
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/src/common/serializer/binary_serializer.cpp>
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/src/common/serializer/binary_deserializer.cpp>
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/src/common/serializer/buffered_file_reader.cpp>
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/src/common/serializer/buffered_file_writer.cpp>
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/src/common/serializer/memory_stream.cpp>
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/src/common/serializer/serializer.cpp>
