// Unity Build generated by CMake
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/src/common/arrow/appender/bool_data.cpp>
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/src/common/arrow/appender/fixed_size_list_data.cpp>
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/src/common/arrow/appender/null_data.cpp>
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/src/common/arrow/appender/struct_data.cpp>
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/src/common/arrow/appender/union_data.cpp>
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/src/common/arrow/appender/append_data.cpp>
