// Unity Build generated by CMake
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/src/common/adbc/nanoarrow/metadata.cpp>
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/src/common/adbc/nanoarrow/schema.cpp>
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/src/common/adbc/nanoarrow/allocator.cpp>
#include </Users/ravi/Documents/Dev/duckDBSP/duckdb/src/common/adbc/nanoarrow/single_batch_array_stream.cpp>
